num1 = int(input("Ingrese un numero entero distinto de 0: "))
num2 = int(input("Ingrese un segundo numero entero distinto de 0: "))
print(num1 + num2)
print(num1 - num2)
print(num1 * num2)
print(num1 / num2)